Implements the error message for no driver
variant-inc/react-native-variant-chat pull request #39
Opened 2021-12-17 22:03 UTC by elonmitchell

Problem
=======
Implements the error message for no driver
[link to JIRA RGR-X](https://usxtech.atlassian.net/browse/RGR-X)

Solution
========
- Implemented the error message for no driver

Screenshots (optional):
-----------------------
Screenshot of Android device

2021-12-17 22:43 UTC, ajp8164 requested changes
Can you please also update the readme with the new error?

2021-12-17 22:43 UTC, ajp8164 commented on src/hooks/useFreshchat.ts
> +        const { graphQLErrors } = error;
The messaging api via shift doesn’t return errors at the transport layer (not this kind). The content of the response body has error properties that should be looked at for this “404” error. It really should not be a 404 code as it’s confusing - the call to the service will return a 200 in this case.

2021-12-21 15:33 UTC, antonyermolayev approved these changes

2021-12-22 14:41 UTC, ajp8164 approved these changes
ACK

2021-12-22 15:01 UTC, merged