Rgr 657 format of urgent messages on roger
variant-inc/react-native-variant-chat pull request #47
Opened 2022-01-13 21:56 UTC by ccouvillion6

Problem
=======
Urgent messages should have a subtitle of "Audible In-Cab Only" on platforms other than PS tablet
(https://usxtech.atlassian.net/browse/RGR-657)

Solution
========
Added an appName parameter when the chat component is initialized; changed the message rendered depending on the app name

Screenshots:
-----------------------
[Screenshots to be added later]

2022-01-14 15:42 UTC, ajp8164 requested changes

2022-01-14 15:42 UTC, ajp8164 commented on src/components/Bubble.tsx
> +      if (appName === 'Ops Chat') {
Please don't do this. We want the chat component to be 100% agnostic to is consumer. Knowing the specific app and making decisions in the component binds maintenance of the component to consuming app feature changes. Alternatively we can provide a way to pass in a component to override the chat components default behavior in this instance. As an example of this pattern see the RN section list (https://reactnative.dev/docs/sectionlist#listemptycomponent).

The component passed into <VariantChat ...> in Ops Chat should be as follows. The styles will have to be extracted into the consuming app.

`<Text style={styles.content.textTick}>Audible Message</Text>
            <SvgXml
              style={styles.content.iconMic}
              xml={getSvg('iconMic')}
              accessibilityLabel="mic"
            />`

2022-01-14 15:42 UTC, ajp8164 commented on src/components/Bubble.tsx
> +            <Text style={styles.content.textTick}>Audible In-Cab Only</Text>
Same comment as above. We should provide the following as a component in the context of the <VariantChat ...> component call from Roger/Ops Chat.

`<Text style={styles.content.textTick}>Audible In-Cab Only</Text>`

2022-01-17 20:52 UTC, antonyermolayev requested changes

2022-01-17 20:52 UTC, antonyermolayev commented on src/components/Bubble.tsx
> +  urgentMessageComponent?: JSX.Element;
Can we just use a specific style rather than introducing a new component?

2022-01-17 20:57 UTC, antonyermolayev commented on src/components/Message.tsx
> +  urgentMessageComponent?: JSX.Element;
If urgentMessage is just about changing a background color, you can do it in containerStyle for the Message component instead of introducing a new component

2022-01-17 21:05 UTC, ajp8164 approved these changes
LGTM

2022-01-17 21:06 UTC, ajp8164 approved these changes
LGTM

2022-01-17 21:06 UTC, ajp8164 commented on src/components/Bubble.tsx
> +  urgentMessageComponent?: JSX.Element;
Based on my understanding of the requirements, roger and ops chat have different ui’s for the display of urgent message. It’s different enough to require a component rather than parameterize a single embedded implementation. As this component evolves we will likely add more component passing so that over time this component is rarely if ever touched. This approach promotes more stable implementation than continuing to add switch logic.

2022-01-17 21:12 UTC, abaidusx commented on src/components/Message.tsx
> +  urgentMessageComponent?: JSX.Element;
There are two different text for Roger and Ops Chat.
So @ccouvillion6 ended up passing the component. We kept the original UI as default.

2022-01-17 21:12 UTC, antonyermolayev commented on src/components/Bubble.tsx
> +  urgentMessageComponent?: JSX.Element;
ok, that's fine then. I originally thought that the whole message should have a different background color in case it's urgent.

2022-01-17 21:12 UTC, antonyermolayev approved these changes

2022-01-17 21:14 UTC, taj-averylane approved these changes

2022-01-17 21:14 UTC, taj-averylane commented on src/components/Bubble.tsx
> +          <View style={styles.content.audibleContainer as StyleProp<ViewStyle>}>
The type casting looks needless

```suggestion
          <View style={styles.content.audibleContainer}>
```

2022-01-17 21:14 UTC, taj-averylane commented on src/components/Chat.tsx
> +      textDecorationLine: 'underline',
This fix was already merged in the develop.
https://github.com/variant-inc/react-native-variant-chat/blob/develop/src/components/Chat.tsx#L383

You'll have to pull the latest develop branch.

2022-01-17 21:16 UTC, merged